implement auto-sort for UniqueListingList
AY2223S1-CS2103T-W15-2/tp pull request #60
Opened 2022-10-15 08:57 UTC by hoang227

2022-10-15 09:21 UTC, jeromehjj requested changes
Just some minor changes and then LGTM!

2022-10-15 09:21 UTC, jeromehjj commented on src/main/java/seedu/address/model/listing/Listing.java
> +     * Compare current listing to l
```suggestion
     * Compares current listing to l
```

2022-10-15 09:21 UTC, jeromehjj commented on src/main/java/seedu/address/model/listing/UniqueListingList.java
> +        int idx = 0;
I think maybe can change to `index` to make it clearer

2022-10-17 08:07 UTC, Gavzzz approved these changes

2022-10-17 08:07 UTC, Gavzzz commented on src/main/java/seedu/address/model/listing/Listing.java
> +    /**
In line 29 isit possible to change  private final List<Person> interestedClients, to List<Client> interestedClients to be more specific?

2022-10-18 18:06 UTC, jeromehjj approved these changes
LGTM!

2022-10-20 07:54 UTC, merged